{
  "schema_version": "1.5.0",
  "id": "BIT-gitlab-2020-13328",
  "details": "An issue has been discovered in GitLab affecting versions prior to 13.1.2, 13.0.8 and 12.10.13. GitLab was vulnerable to a stored XSS by using the PyPi files API.",
  "aliases": [
    "CVE-2020-13328"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "gitlab",
        "purl": "pkg:bitnami/gitlab"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "12.0.0"
            },
            {
              "fixed": "12.10.13"
            },
            {
              "introduced": "13.0.0"
            },
            {
              "fixed": "13.0.8"
            },
            {
              "introduced": "13.1.0"
            },
            {
              "fixed": "13.1.2"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Medium",
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13328.json"
    },
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/215640"
    }
  ],
  "published": "2024-03-06T11:22:02.327Z",
  "modified": "2024-03-06T11:25:28.861Z"
}