{
  "schema_version": "1.5.0",
  "id": "BIT-2020-13281",
  "details": "For GitLab before 13.0.12, 13.1.6, 13.2.3 a denial of service exists in the project import feature",
  "aliases": [
    "CVE-2020-13281"
  ],
  "affected": [
    {
      "packages": [
        {
          "ecosystem": "bitnami",
          "name": "gitlab",
          "purl": "pkg:bitnami/gitlab"
        }
      ],
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "8.9.0"
            },
            {
              "fixed": "13.0.12"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "13.1.0"
            },
            {
              "fixed": "13.1.6"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "13.2.0"
            },
            {
              "fixed": "13.2.3"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Medium",
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13281.json"
    },
    {
      "type": "WEB",
      "url": "https://hackerone.com/reports/687730"
    }
  ],
  "published": "2023-06-12T14:34:09.345Z",
  "modified": "2023-06-12T14:35:05.390Z"
}