{
  "id": "CVE-2022-1428",
  "package_name": "gitlab",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:gitlab:gitlab:14.10.0:*:*:*:community:*:*:*",
    "cpe:2.3:a:gitlab:gitlab:14.10.0:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*"
  ],
  "version_constraint": "< 14.8.6 || < 14.8.6 || >= 14.9.0, < 14.9.4 || >= 14.9.0, < 14.9.4 || = 14.10.0 || = 14.10.0",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "An issue has been discovered in GitLab affecting all versions before 14.8.6, all versions starting from 14.9 before 14.9.4, all versions starting from 14.10 before 14.10.1. GitLab was incorrectly verifying throttling limits for authenticated package requests which resulted in limits not being enforced.",
  "urls": [
    "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-1428.json",
    "https://gitlab.com/gitlab-org/gitlab/-/issues/342481"
  ]
}
