{
  "schema_version": "1.6.2",
  "id": "BIT-pytorch-2025-55554",
  "details": "pytorch v2.8.0 was discovered to contain an integer overflow in the component torch.nan_to_num-.long().",
  "aliases": [
    "CVE-2025-55554"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "pytorch",
        "purl": "pkg:bitnami/pytorch"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "2.8.0"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Medium",
    "cpes": [
      "cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytorch/pytorch/issues/151510"
    },
    {
      "type": "WEB",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-55554"
    }
  ],
  "published": "2025-10-04T23:49:06.307Z",
  "modified": "2025-10-05T00:07:21.198Z"
}