{
  "schema_version": "1.6.2",
  "id": "BIT-libpython-2022-26488",
  "details": "In Python before 3.10.3 on Windows, local users can gain privileges because the search path is inadequately secured. The installer may allow a local attacker to add user-writable directories to the system search path. To exploit, an administrator must have installed Python for all users and enabled PATH entries. A non-administrative user can trigger a repair that incorrectly adds user-writable paths into PATH, enabling search-path hijacking of other users and system services. This affects Python (CPython) through 3.7.12, 3.8.x through 3.8.12, 3.9.x through 3.9.10, and 3.10.x through 3.10.2.",
  "aliases": [
    "CVE-2022-26488"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "libpython",
        "purl": "pkg:bitnami/libpython"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "3.7.12"
            },
            {
              "introduced": "3.8.0"
            },
            {
              "last_affected": "3.8.12"
            },
            {
              "introduced": "3.9.0"
            },
            {
              "last_affected": "3.9.10"
            },
            {
              "introduced": "3.10.0"
            },
            {
              "last_affected": "3.10.2"
            },
            {
              "introduced": "3.11.0-alpha1"
            },
            {
              "last_affected": "3.11.0-alpha1"
            },
            {
              "introduced": "3.11.0-alpha2"
            },
            {
              "last_affected": "3.11.0-alpha2"
            },
            {
              "introduced": "3.11.0-alpha3"
            },
            {
              "last_affected": "3.11.0-alpha3"
            },
            {
              "introduced": "3.11.0-alpha4"
            },
            {
              "last_affected": "3.11.0-alpha4"
            },
            {
              "introduced": "3.11.0-alpha5"
            },
            {
              "last_affected": "3.11.0-alpha5"
            },
            {
              "introduced": "3.11.0-alpha6"
            },
            {
              "last_affected": "3.11.0-alpha6"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "High",
    "cpes": [
      "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://mail.python.org/archives/list/security-announce%40python.org/thread/657Z4XULWZNIY5FRP3OWXHYKUSIH6DMN/"
    },
    {
      "type": "WEB",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-26488"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20220419-0005/"
    }
  ],
  "published": "2025-08-11T13:52:02.378Z",
  "modified": "2025-09-10T09:09:35.631Z"
}