{
  "id": "CVE-2018-14859",
  "package_name": "odoo",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:odoo:odoo:9.0:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:odoo:odoo:10.0:*:*:*:community:*:*:*",
    "cpe:2.3:a:odoo:odoo:10.0:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:odoo:odoo:11.0:*:*:*:community:*:*:*",
    "cpe:2.3:a:odoo:odoo:11.0:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:odoo:odoo:9.0:*:*:*:community:*:*:*"
  ],
  "version_constraint": "= 9.0 || = 9.0 || = 10.0 || = 10.0 || = 11.0 || = 11.0",
  "fixed_in_versions": "null",
  "severity": "High",
  "description": "Incorrect access control in the password reset component in Odoo Community 11.0 and earlier and Odoo Enterprise 11.0 and earlier allows authenticated users to reset the password of other users by being the first party to use the secure token.",
  "urls": [
    "https://github.com/odoo/odoo/issues/32510"
  ]
}
