{
  "id": "CVE-2017-10803",
  "package_name": "odoo",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:odoo:odoo:10.0:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:odoo:odoo:8.0:*:*:*:*:*:*:*",
    "cpe:2.3:a:odoo:odoo:9.0:*:*:*:community:*:*:*",
    "cpe:2.3:a:odoo:odoo:9.0:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:odoo:odoo:10.0:*:*:*:community:*:*:*"
  ],
  "version_constraint": "= 8.0 || = 9.0 || = 9.0 || = 10.0 || = 10.0",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "In Odoo 8.0, Odoo Community Edition 9.0 and 10.0, and Odoo Enterprise Edition 9.0 and 10.0, insecure handling of anonymization data in the Database Anonymization module allows remote authenticated privileged users to execute arbitrary Python code, because unpickle is used.",
  "urls": [
    "https://github.com/odoo/odoo/issues/17898"
  ]
}
