{
  "schema_version": "1.5.0",
  "id": "CVE-2015-7384",
  "details": "Node.js 4.0.0, 4.1.0, and 4.1.1 allows remote attackers to cause a denial of service.",
  "aliases": [
    "CVE-2015-7384"
  ],
  "affected": [
    {
      "packages": [
        {
          "ecosystem": "bitnami",
          "name": "node",
          "purl": "pkg:bitnami/node"
        }
      ],
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "versions": [
        "4.0.0",
        "4.1.0",
        "4.1.1"
      ]
    }
  ],
  "database_specific": {
    "severity": "High",
    "cpes": [
      "cpe:2.3:a:nodejs:node.js:4.0.0:*:*:*:*:*:*:*",
      "cpe:2.3:a:nodejs:node.js:4.1.0:*:*:*:*:*:*:*",
      "cpe:2.3:a:nodejs:node.js:4.1.1:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "http://www.securityfocus.com/bid/101260"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1268791"
    },
    {
      "type": "WEB",
      "url": "https://github.com/nodejs/node/issues/3138"
    }
  ],
  "published": "2023-05-30T11:32:49.683Z",
  "modified": "2023-05-30T11:32:49.683Z"
}