{
  "id": "CVE-2021-4189",
  "package_name": "python",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:python:python:3.10.0:-:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
  ],
  "version_constraint": ">= 3.6.0, < 3.6.14 || >= 3.7.0, < 3.7.11 || >= 3.8.0, < 3.8.9 || >= 3.9.0, < 3.9.3 || = 3.10.0",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible.",
  "urls": [
    "https://access.redhat.com/security/cve/CVE-2021-4189",
    "https://bugs.python.org/issue43285",
    "https://bugzilla.redhat.com/show_bug.cgi?id=2036020",
    "https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e",
    "https://python-security.readthedocs.io/vuln/ftplib-pasv.html",
    "https://security-tracker.debian.org/tracker/CVE-2021-4189",
    "https://security.netapp.com/advisory/ntap-20221104-0004/"
  ]
}
