{
  "schema_version": "1.5.0",
  "id": "BIT-django-2024-38875",
  "details": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.",
  "aliases": [
    "CVE-2024-38875"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "django",
        "purl": "pkg:bitnami/django"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "4.2.0"
            },
            {
              "fixed": "4.2.14"
            },
            {
              "introduced": "5.0.0"
            },
            {
              "fixed": "5.0.7"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "High",
    "cpes": [
      "cpe:2.3:a:djangoproject:django:*:*:*:*:*:python:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://docs.djangoproject.com/en/dev/releases/security/"
    },
    {
      "type": "WEB",
      "url": "https://groups.google.com/forum/#%21forum/django-announce"
    },
    {
      "type": "WEB",
      "url": "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"
    }
  ],
  "published": "2025-03-08T19:08:17.356Z",
  "modified": "2025-03-08T19:47:10.211Z"
}