{
  "id": "CVE-2021-45115",
  "package_name": "django",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
  ],
  "version_constraint": ">= 2.2, < 2.2.26 || >= 3.2, < 3.2.11 || >= 4.0, < 4.0.1",
  "fixed_in_versions": "null",
  "severity": "High",
  "description": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack.",
  "urls": [
    "https://docs.djangoproject.com/en/4.0/releases/security/",
    "https://groups.google.com/forum/#!forum/django-announce",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/",
    "https://security.netapp.com/advisory/ntap-20220121-0005/",
    "https://www.djangoproject.com/weblog/2022/jan/04/security-releases/"
  ]
}
