{
  "id": "CVE-2022-33099",
  "package_name": "lua",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:lua:lua:*:*:*:*:*:*:*:*"
  ],
  "version_constraint": ">= 5.4.2, <= 5.4.4",
  "fixed_in_versions": "null",
  "severity": "High",
  "description": "An issue in the component luaG_runerror of Lua v5.4.4 and below leads to a heap-buffer overflow when a recursive error occurs.",
  "urls": [
    "https://github.com/lua/lua/commit/42d40581dd919fb134c07027ca1ce0844c670daf",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RJNJ66IFDUKWJJZXHGOLRGIA3HWWC36R/",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UHYZOEFDVLVAD6EEP4CDW6DNONIVVHPA/",
    "https://lua-users.org/lists/lua-l/2022-05/msg00035.html",
    "https://lua-users.org/lists/lua-l/2022-05/msg00042.html",
    "https://lua-users.org/lists/lua-l/2022-05/msg00073.html",
    "https://www.lua.org/bugs.html#Lua-stack%20overflow%20when%20C%20stack%20overflows%20while%20handling%20an%20error:~:text=Lua%2Dstack%20overflow%20when%20C%20stack%20overflows%20while%20handling%20an%20error"
  ]
}
